server:
  port: 8081

spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${DB_HOST:localhost}:3306/productdb
    username: root
    password: MySqlPass*
  jpa:
    hibernate:
      ddl-auto: update
    generate-ddl: true
    show-sql: true
  application:
    name: PRODUCT-SERVICE
  config:
    import: configserver:http://localhost:9296

#eureka:
#  instance:
#    prefer-ip-address: true
#  client:
#    fetch-registry: true
#    register-with-eureka: true
#    service-url:
#      defaultZone: ${EUREKA_SERVER_ADDRESS:http://localhost:8761/eureka}